= Project: {Robot-Navigating-Map-Sketching}

=== Author: azmm12.
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 22/08/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Simulating a Robot on a map to recognize the map and sketch it then printing it on an image .

== Steps:
1. Open Virtual box .
2. Start Ubuntu .
3. Clean catkin_ws and Type commands in "Turtlebot3.txt" to the terminal of ubuntu to Download pakages of turtlebot3 .

=== Part 1:Navigating the robot through the map
....
1. Open a New Terminal .
2. Type : 
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_gazebo turtlebot3_world.launch

Now Gazebo will launch

3. Open another terminal .
4. Type :
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

5. Now you can navigate using  W = Forward , S = Stop , D = Right , A = Left .
....
=== Part 2:recognizing and sketching the map
....
1. Open a New Terminal .
2. Type : 
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_gazebo turtlebot3_world.launch

Now Gazebo will launch

3. Open another terminal .
4. Type :
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=gmapping 

Now Rviz will launch

5. Open another terminal .
6. Type :
export TURTLEBOT3_MODEL=burger
roslaunch turtlebot3_teleop turtlebot3_teleop_key.launch

7. Now you can navigate using  W = Forward , S = Stop , D = Right , A = Left .
8. Navigate through all the map untill you see the map picture on Rviz is clear .
9. Open another terminal
10. Type:
rosrun map_server map_saver -f ~/map

Now the map is saved 
....


=== Folder structure

....
 ROS_Task_2
  └── README.adoc                    => this file
  └── Turtlebot3.txt                 => Commands to install file
  └── Part 1 Pictures                => picture of Simulation
  └── Part 2 Pictures                => picture of Simulation
  └── Printed Map Files              => picture of Simulation
....
